title: csc-301-final
description: >-
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/csc301final.github.io/"
url: "https://austinmreppert.github.io"


markdown: github

minimal_mistakes_skin: "dark"
remote_theme: "mmistakes/minimal-mistakes"

search: true

plugins:
    - jekyll-include-cache

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      show_date: true
      read_time: true
